name: Deploy Portfolio
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions_website_deploy
          chmod 600 ~/.ssh/github_actions_website_deploy
          echo -e "Host 45.76.34.39\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/github_actions_website_deploy\n\tPreferredAuthentications publickey\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
          --exclude=".git" \
          --exclude=".github" \
          --exclude="node_modules" \
          -e "ssh -i ~/.ssh/github_actions_website_deploy" \
          ./ root@45.76.34.39:/var/www/alacer.pl
          
      - name: Setup and Start Next.js Application
        run: |
          ssh -i ~/.ssh/github_actions_website_deploy root@45.76.34.39 "
            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            cd /var/www/alacer.pl
            
            # Install production dependencies
            npm install --production
            
            # Check if the Next.js app is already running in PM2
            if pm2 list | grep -q 'alacer.pl'; then
              pm2 reload alacer.pl
            else
              # Start the Next.js app with PM2
              PORT=3001 pm2 start npm --name "alacer.pl" -- start
            fi
            
            # Save PM2 process list to automatically restart on server reboot
            pm2 save
          "